
/** @typedef {{ id: string, text: string }} ReflectionPromptItem */

/** @type {ReflectionPromptItem[]} */
export const GENERIC_PROMPTS = [
  { id: 'gen-01', text: 'What small moment today deserved more attention than it got?' },
  { id: 'gen-02', text: 'If your mood had a color right now, what would it be—and why?' },
  { id: 'gen-03', text: 'What is one thing your body or breath is asking for today?' },
  { id: 'gen-04', text: 'Who or what helped you feel a little more human recently?' },
  { id: 'gen-05', text: 'What would “enough” look like for you this week?' },
  { id: 'gen-06', text: 'What story are you telling yourself—and is there a gentler version?' },
  { id: 'gen-07', text: 'What would you thank your past self for, even if it was tiny?' },
  { id: 'gen-08', text: 'Where did you notice beauty or softness today?' },
  { id: 'gen-09', text: 'What boundary would protect your peace tomorrow?' },
  { id: 'gen-10', text: 'What feeling do you want to carry into tonight’s rest?' },
  { id: 'gen-11', text: 'If today had a chapter title, what would it be?' },
  { id: 'gen-12', text: 'What are you learning about yourself lately—without judgment?' },
  { id: 'gen-13', text: 'What habit is quietly shaping your weeks?' },
  { id: 'gen-14', text: 'Where did patience show up without applause?' },
  { id: 'gen-15', text: 'What would you do with an hour truly unscheduled?' },
  { id: 'gen-16', text: 'What fear shrunk when you named it?' },
  { id: 'gen-17', text: 'Who deserves a thank-you you have not sent?' },
  { id: 'gen-18', text: 'What did you almost skip that turned out to matter?' },
]

function moodItems(id, texts) {
  return texts.map((text, i) => ({
    id: `${id}-${String(i + 1).padStart(2, '0')}`,
    text,
  }))
}

/** @type {Record<string, ReflectionPromptItem[]>} */
export const MOOD_PROMPTS = {
  peaceful: moodItems('peaceful', [
    'Where did you find stillness today—even for a breath?',
    'What noise could you turn down in your mind or your schedule?',
    'What does “enough calm” feel like in your body?',
    'Who allows you to exhale when you are with them?',
    'What sound or silence nourished you today?',
    'Where does your breath land when you soften your shoulders?',
    'What could wait without the world ending?',
    'What gentle boundary protected your peace?',
    'When did you choose slowness on purpose?',
    'What view—literal or mental—felt spacious?',
    'What would feel sacred if you treated it as ritual?',
    'Who models calm you would like to borrow for a moment?',
    'What tiny ritual signals “I am home” to you?',
    'What are you releasing with your exhale tonight?',
    'What word would you whisper to yourself before sleep?',
  ]),
  joyful: moodItems('joyful', [
    'What made you smile before your brain could explain it?',
    'Where did joy show up in a small, ordinary place?',
    'What would you replay from today if you had a highlight reel?',
    'How could you share a slice of this lightness with someone else?',
    'Where did laughter sneak in uninvited?',
    'What tiny win are you proud to admit?',
    'Who reflects your joy back to you?',
    'What song matches your heartbeat today?',
    'What color is your optimism right now?',
    'What did you celebrate that others might skip?',
    'What invitation to joy did you almost decline?',
    'Where did gratitude spike without effort?',
    'What would your inner child cheer for today?',
    'What moment felt unfairly good?',
    'What are you saying yes to that feeds joy?',
  ]),
  reflective: moodItems('reflective', [
    'What question is sitting unfinished in the back of your mind?',
    'What pattern are you ready to understand—not fix?',
    'What truth feels scary but clarifying right now?',
    'What would you journal if no one, including you, ever read it?',
    'What conversation are you replaying—and what would closure sound like?',
    'What assumption deserves a second look?',
    'Where are you confusing motion with meaning?',
    'What would honesty cost—and what would it free?',
    'Which feeling keeps tapping your shoulder?',
    'What question would you ask if you were not afraid of the answer?',
    'What are you outgrowing without admitting it?',
    'What insight keeps returning until you listen?',
    'Where did silence teach you something noise could not?',
    'What label no longer fits?',
    'What would integration feel like here—not fixing?',
  ]),
  energized: moodItems('energized', [
    'Where do you want to aim this spark today?',
    'What would make this energy sustainable—not just intense?',
    'Who benefits when you show up with this drive?',
    'What is one bold step that still feels aligned?',
    'What fuel are you running on—spark or pressure?',
    'Where does your momentum feel kindest?',
    'What finish line would actually satisfy you?',
    'What rest would make tomorrow’s fire cleaner?',
    'Who charges you without draining you?',
    'What idea pulled you upright today?',
    'Where did enthusiasm meet patience?',
    'What would sustainable excitement look like this week?',
    'What are you racing toward—and is it still yours?',
    'What stretch felt brave without being reckless?',
    'What signal tells you “enough for today”?',
  ]),
  tender: moodItems('tender', [
    'What part of you needs softness instead of solutions?',
    'What ache are you holding gently today?',
    'What would comfort sound like if it were a sentence?',
    'Who holds space for you without trying to fix you?',
    'What wound asks for witness, not repair?',
    'Where did gentleness surprise you?',
    'What apology—to yourself—still waits?',
    'Who saw you clearly today?',
    'What softness did you mistake for weakness?',
    'Where does vulnerability feel safest lately?',
    'What hug—literal or metaphor—do you need?',
    'What tears arrived without a villain?',
    'Where did you mother yourself well?',
    'What boundary guards your tenderness?',
    'What “too much” feeling is actually honest?',
  ]),
  hopeful: moodItems('hopeful', [
    'What tiny evidence suggests tomorrow could be kinder?',
    'What future moment are you quietly rooting for?',
    'What strength have you underestimated in yourself?',
    'What would "progress" look like if it were gentle?',
    'What bridge between today and tomorrow feels sturdy?',
    'What seed did you plant without proof yet?',
    'Who reminds you that change is slow but real?',
    'What possibility feels fragile but worth guarding?',
    'Where did hope cost less than cynicism?',
    'What small upward motion did you notice?',
    'What future self are you practicing being?',
    'What light leak appeared under the door?',
    'What support would make hope easier to hold?',
    'What are you willing to try again gently?',
    'What morning thought steadies your chest?',
  ]),
  grounded: moodItems('grounded', [
    'What root—routine, place, or person—steadies you lately?',
    'Where do you feel your feet today, literally or metaphorically?',
    'What simple ritual brings you back to now?',
    'What truth can you name without spinning a story around it?',
    'What anchor helped when thoughts raced?',
    'What texture—fabric, earth, wood—settled you?',
    'Where did your attention land without negotiation?',
    'What routine protects your nervous system?',
    'Who speaks plainly and helps you land?',
    'What fact calmed a spiral today?',
    'Where did you choose feet-first over fantasy?',
    'What meal, stretch, or sip brought you back?',
    'What story did your body believe?',
    'What permission to be ordinary did you accept?',
    'What ground will you stand on tomorrow?',
  ]),
  wistful: moodItems('wistful', [
    'What chapter are you closing—or longing to reopen?',
    'What memory surfaces softly when you slow down?',
    'What do you miss—and what does that say about what you value?',
    'If you wrote a letter to a past version of you, what would you thank them for?',
    'What almost was still visits you kindly?',
    'Where does longing point—not backward only?',
    'What song carries a season you miss?',
    'Who represents a road not taken without regret?',
    'What sweetness tinged with ache showed up today?',
    'What door stays ajar in your imagination?',
    'Where did nostalgia soften instead of sting?',
    'What would you preserve from that chapter?',
    'What gratitude lives inside missing?',
    'What gentle goodbye are you rehearsing?',
    'What beauty feels unreachable—but close?',
  ]),
  playful: moodItems('playful', [
    'Where could you let things be a little silly on purpose?',
    'What made you laugh like nobody was grading you?',
    'What experiment—tiny—could break up the seriousness?',
    'How did you play as a kid that your adult self forgets?',
    'What rule did you bend playfully and survive?',
    'Where did curiosity replace critique?',
    'What game—literal or mental—lifted your mood?',
    'Who brings out your ridiculous side safely?',
    'What costume does your seriousness wear?',
    'Where did spontaneity reward you?',
    'What laugh loosened your jaw?',
    'What playful risk paid off tiny?',
    'Where could whimsy solve what grind could not?',
    'What dance move did your mood attempt?',
    'What fun are you rationing that you could spend?',
  ]),
  resilient: moodItems('resilient', [
    'What obstacle have you survived that you rarely credit?',
    'What did you do today that required quiet courage?',
    'Who believes in you on the days you don’t?',
    'What “not yet” are you willing to keep showing up for?',
    'What quiet courage did you repeat until it became muscle?',
    'When did pausing feel braver than pushing?',
    'What bend-without-breaking moment are you proud of?',
    'What scar tells a story you respect?',
    'What resource—sleep, food, friend—replenished resolve?',
    'What boundary restored your strength?',
    'What comeback began smaller than pride allowed?',
    'What practice makes hard days survivable?',
    'What proof of grit did you dismiss as normal?',
    'Where did you choose repair over retreat?',
    'What steady step counts more than a leap?',
  ]),
}
