export const MOOD_OPTIONS = [
  {
    id: 'peaceful',
    label: 'Peaceful',
    emoji: '😌',
    swatch: '#78C0A8',
    accent: 'from-teal-200/70 to-teal-400/40',
    tags: ['calm', 'centered'],
  },
  {
    id: 'joyful',
    label: 'Joyful',
    emoji: '😊',
    swatch: '#F7A399',
    accent: 'from-peach-200/80 to-peach-400/40',
    tags: ['uplifted', 'grateful'],
  },
  {
    id: 'reflective',
    label: 'Reflective',
    emoji: '🤔',
    swatch: '#EAEAEA',
    accent: 'from-neutral-200/80 to-neutral-400/40',
    tags: ['thoughtful'],
  },
  {
    id: 'energized',
    label: 'Energized',
    emoji: '✨',
    swatch: '#C9A7EB',
    accent: 'from-purple-200/70 to-purple-400/40',
    tags: ['motivated'],
  },
  {
    id: 'tender',
    label: 'Tender',
    emoji: '🥲',
    swatch: '#B8C4FF',
    accent: 'from-sky-200/80 to-sky-400/40',
    tags: ['soft', 'sensitive'],
  },
  {
    id: 'hopeful',
    label: 'Hopeful',
    emoji: '🌤️',
    swatch: '#F5C26B',
    accent: 'from-amber-200/70 to-amber-400/40',
    tags: ['optimistic', 'forward'],
  },
  {
    id: 'grounded',
    label: 'Grounded',
    emoji: '🌿',
    swatch: '#7DA67A',
    accent: 'from-green-200/70 to-green-400/40',
    tags: ['steady', 'present'],
  },
  {
    id: 'wistful',
    label: 'Wistful',
    emoji: '🌙',
    swatch: '#9BB0C6',
    accent: 'from-slate-200/80 to-slate-400/40',
    tags: ['nostalgic', 'longing'],
  },
  {
    id: 'playful',
    label: 'Playful',
    emoji: '🎈',
    swatch: '#FF8DA1',
    accent: 'from-rose-200/70 to-rose-400/40',
    tags: ['light', 'fun'],
  },
  {
    id: 'resilient',
    label: 'Resilient',
    emoji: '💪',
    swatch: '#D4A574',
    accent: 'from-orange-200/60 to-orange-400/40',
    tags: ['strong', 'capable'],
  },
];

export const getMoodById = (id) => MOOD_OPTIONS.find((mood) => mood.id === id) ?? null;

